#!/bin/sh
### lolcommits hook (begin) ###
if [ ! -d "$GIT_DIR/rebase-merge" ]; then
export LANG="en_GB.UTF-8"
export PATH="/Users/emils.solmanis/.rvm/rubies/ruby-2.4.0/bin:/usr/local/bin:$PATH"
lolcommits --capture
fi
###  lolcommits hook (end)  ###
