set fish_user_abbreviations $fish_user_abbreviations "gs=git status -s"
set fish_user_abbreviations $fish_user_abbreviations "gl=git log"
set fish_user_abbreviations $fish_user_abbreviations "gd=git diff"
set fish_user_abbreviations $fish_user_abbreviations "gcm=git commit -m"
set fish_user_abbreviations $fish_user_abbreviations "gco=git checkout"
set fish_user_abbreviations $fish_user_abbreviations "ga=git add"
